name: Test db-scxa operations

on: [pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Add workspace to path
      run: |
        echo "${GITHUB_WORKSPACE}" >> $GITHUB_PATH
    
    - uses: docker-practice/actions-setup-docker@master
    - run: |
        run_tests_with_containers.sh
